data:
  root: /home/voz/shared/database/sed
  dataset: ESC-50
  num_mel_bins: 128
  sample_frequency: 16000
  frame_length: 25
  frame_shift: 10
  window_type: hanning
  freq_mask_param: 24
  time_mask_param: 96

encoder:
  arch: ast
  path: /home/voz/almudevar/distribution_distance_loss/models/AST/audioset_10_10_0.4593.pth

optimizer:
  optimizer: ADAM
  lr: 0.0000067
  batch_size: 32
  betas: [0.95, 0.999]
  weight_decay: 0.000005

scheduler:
  epochs: 25
  lr_decay_rate: 0.85
  lr_decay_epochs: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
  cosine: False
  warm_epochs: 5